services:
  backend:
    build: ./backend
    ports:
      - "3004:3004"  # Map backend port 3004 to host
    volumes:
      - ./backend:/app  # Mount local backend directory to container
    environment:
      - PYTHONUNBUFFERED=1  # Ensure output isn't buffered (important for logging)
    depends_on:
      - db  # Ensure the database starts before the backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Map frontend port 3000 to host
    volumes:
      - ./frontend:/app  # Mount local frontend directory to container
      - /app/node_modules  # Prevent issues with node_modules in container
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot-reloading in Docker
    depends_on:
      - backend  # Ensure backend starts before frontend

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map PostgreSQL port 5432 to host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    environment:
      - POSTGRES_DB=mydatabase  # Set the database name
      - POSTGRES_USER=myuser  # Set the database user
      - POSTGRES_PASSWORD=mypassword  # Set the database password

volumes:
  postgres_data:
